/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lpoo.gui;

import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author MARQUES
 */
public class GUIMazeEditor extends javax.swing.JFrame {

    private char btnSymbol;

    private final JFileChooser fin = new JFileChooser();
    private final JFileChooser fout = new JFileChooser();

    /**
     * Creates new form GUIMazeEditor
     */
    public GUIMazeEditor() 
    {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/lpoo/res/editor-128x128.png")));
        btnSymbol = ' ';
    }

    public void setMazeSize(int w, int h) 
    {
        areaEdicao1 = new AreaEdicao(w, h);
        areaEdicao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        areaEdicao1.setMinimumSize(new java.awt.Dimension(64, 64));
        areaEdicao1.setPreferredSize(new java.awt.Dimension(640, 480));
        areaEdicao1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                areaEdicao1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout areaEdicao1Layout = new javax.swing.GroupLayout(areaEdicao1);
        areaEdicao1.setLayout(areaEdicao1Layout);
        areaEdicao1Layout.setHorizontalGroup(
            areaEdicao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        areaEdicao1Layout.setVerticalGroup(
            areaEdicao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(areaEdicao1);
        buttonGroup1.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnDart1 = new javax.swing.JToggleButton();
        btnPlayer = new javax.swing.JToggleButton();
        btnDragon = new javax.swing.JToggleButton();
        btnShield = new javax.swing.JToggleButton();
        btnShield1 = new javax.swing.JToggleButton();
        btnDart = new javax.swing.JToggleButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnDart2 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaEdicao1 = new lpoo.gui.AreaEdicao();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maze Editor");

        jToolBar1.setRollover(true);

        btnDart1.setBackground(new java.awt.Color(255, 153, 102));
        buttonGroup1.add(btnDart1);
        btnDart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/wall-32x32.png"))); // NOI18N
        btnDart1.setText("Wall");
        btnDart1.setFocusable(false);
        btnDart1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnDart1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDart1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDart1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDart1);

        buttonGroup1.add(btnPlayer);
        btnPlayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/hero-32x32.png"))); // NOI18N
        btnPlayer.setText("Player");
        btnPlayer.setFocusable(false);
        btnPlayer.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnPlayer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPlayer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayerActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPlayer);

        buttonGroup1.add(btnDragon);
        btnDragon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/dragon-32x32.png"))); // NOI18N
        btnDragon.setText("Dragon");
        btnDragon.setFocusable(false);
        btnDragon.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnDragon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDragon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDragon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDragonActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDragon);

        buttonGroup1.add(btnShield);
        btnShield.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/shield-32x32.png"))); // NOI18N
        btnShield.setText("Shield");
        btnShield.setFocusable(false);
        btnShield.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnShield.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShield.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShieldActionPerformed(evt);
            }
        });
        jToolBar1.add(btnShield);

        buttonGroup1.add(btnShield1);
        btnShield1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/sword-32x32.png"))); // NOI18N
        btnShield1.setText("Sword");
        btnShield1.setFocusable(false);
        btnShield1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnShield1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShield1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnShield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShield1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnShield1);

        buttonGroup1.add(btnDart);
        btnDart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/dart-32x32.png"))); // NOI18N
        btnDart.setText("Dart");
        btnDart.setFocusable(false);
        btnDart.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnDart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDart.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDartActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDart);
        jToolBar1.add(jSeparator4);

        buttonGroup1.add(btnDart2);
        btnDart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/eraser-32x32.png"))); // NOI18N
        btnDart2.setText("Erase");
        btnDart2.setFocusable(false);
        btnDart2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnDart2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDart2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDart2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDart2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        areaEdicao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        areaEdicao1.setMinimumSize(new java.awt.Dimension(64, 64));
        areaEdicao1.setPreferredSize(new java.awt.Dimension(640, 480));
        areaEdicao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                areaEdicao1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout areaEdicao1Layout = new javax.swing.GroupLayout(areaEdicao1);
        areaEdicao1.setLayout(areaEdicao1Layout);
        areaEdicao1Layout.setHorizontalGroup(
            areaEdicao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
        );
        areaEdicao1Layout.setVerticalGroup(
            areaEdicao1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(areaEdicao1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("File");

        jMenuItem9.setText("New");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);
        jMenu3.add(jSeparator3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/folder.png"))); // NOI18N
        jMenuItem5.setText("Load");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/disk.png"))); // NOI18N
        jMenuItem6.setText("Save");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/disk_multiple.png"))); // NOI18N
        jMenuItem8.setText("Save As...");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);
        jMenu3.add(jSeparator2);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/door_open.png"))); // NOI18N
        jMenuItem7.setText("Exit");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/arrow_undo.png"))); // NOI18N
        jMenuItem1.setText("Undo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/arrow_redo.png"))); // NOI18N
        jMenuItem2.setText("Redo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);
        jMenu4.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/bomb.png"))); // NOI18N
        jMenuItem3.setText("Clear");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/hourglass.png"))); // NOI18N
        jMenuItem4.setText("Randomize...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("Help");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/information.png"))); // NOI18N
        jMenuItem10.setText("Statistics...");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);
        jMenu1.add(jSeparator5);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lpoo/res/help.png"))); // NOI18N
        jMenuItem11.setText("About");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayerActionPerformed
            areaEdicao1.setSymbol('h');
    }//GEN-LAST:event_btnPlayerActionPerformed

    private void areaEdicao1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaEdicao1MousePressed

    }//GEN-LAST:event_areaEdicao1MousePressed

    private void btnDragonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDragonActionPerformed
        areaEdicao1.setSymbol('D');
        System.out.println("set symbol to dragon");
    }//GEN-LAST:event_btnDragonActionPerformed

    private void btnShieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShieldActionPerformed
        areaEdicao1.setSymbol('V');
    }//GEN-LAST:event_btnShieldActionPerformed

    private void btnDartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDartActionPerformed
        areaEdicao1.setSymbol('*');
    }//GEN-LAST:event_btnDartActionPerformed

    private void btnDart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDart1ActionPerformed
        areaEdicao1.setSymbol('X');
    }//GEN-LAST:event_btnDart1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        areaEdicao1.undo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        areaEdicao1.redo();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        areaEdicao1.generateMaze();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int showOpenDialog = fin.showOpenDialog(this);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (fout.getSelectedFile() == null)
        {
            fout.showSaveDialog(this);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        int showSaveDialog = fout.showSaveDialog(this);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        GUINewMaze g_msize;
        g_msize = new GUINewMaze(this);
        g_msize.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void btnShield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShield1ActionPerformed
        areaEdicao1.setSymbol('E');
    }//GEN-LAST:event_btnShield1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        areaEdicao1.erase();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnDart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDart2ActionPerformed
        areaEdicao1.setSymbol(' ');
    }//GEN-LAST:event_btnDart2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        GUIAbout guiAbout = new GUIAbout(this);
        guiAbout.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
      
        GUIStats guiStats = new GUIStats(this, areaEdicao1.getValues());
        guiStats.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMazeEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIMazeEditor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lpoo.gui.AreaEdicao areaEdicao1;
    private javax.swing.JToggleButton btnDart;
    private javax.swing.JToggleButton btnDart1;
    private javax.swing.JToggleButton btnDart2;
    private javax.swing.JToggleButton btnDragon;
    private javax.swing.JToggleButton btnPlayer;
    private javax.swing.JToggleButton btnShield;
    private javax.swing.JToggleButton btnShield1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
