package lpoo.proj2.audio;

public enum Special
{
	QUAKE_DOUBLEKILL,
	QUAKE_FIRSTBLOOD,
	QUAKE_FLAWLESS,
	QUAKE_GODLIKE,
	QUAKE_HATTRICK,
	QUAKE_HOLYSHIT,
	QUAKE_HUMILIATION,
	QUAKE_KILLINGSPREE,
	QUAKE_PREPARE,
	QUAKE_RAMPAGE
}