package lpoo.proj2.audio;

public enum Special
{
	QUAKE_DOUBLEKILL,
	QUAKE_FIRSTBLOOD,
	QUAKE_FLAWLESS,
	QUAKE_GODLIKE,
	QUAKE_HATTRICK,
	QUAKE_HUMILIATION,
	QUAKE_MONSTERKILL,
	QUAKE_PREPARE,
	QUAKE_RAMPAGE,
	QUAKE_UNSTOPPABLE,
}